<?php
/**
 * acsf function to execute a get request.
 */
function acsfapitools_getcmd($cmdurl = 'ping', $method = 'GET') {
  $url = acsfapitools_conn() . '/' . $cmdurl;
  $response = drupal_http_request($url, $headers = array(),
    $method, $data = NULL, $retry = 3);
  $data = (string) $response->data;
  $data = json_decode($data);
  $code = (string) $response->code;

  if ($code !== '200') {
    drush_set_error(dt("HTTP response code: '!code'", array('!code' => $code)));
  }

  if (drush_get_context('DRUSH_VERBOSE')) {
    (property_exists($data, 'server_time') ?
    drush_print(dt("Server time: '!time'", array('!time' => $data->server_time))) : $error = 'err');
    drush_print(dt("Request url: '!url'", array('!url' => $url)));
    drush_print(dt("Request meathod: '!method'", array('!method' => $method)));
    drush_print(dt("Command: '!cmdurl'", array('!cmdurl' => $cmdurl)));
    drush_print(dt("HTTP response code: '!code'", array('!code' => $code)));
  }

  return $data;
}

/**
 * function to build request url.
 *
 * @TODO cmd line parameters
 */
function acsfapitools_conn($baseurl = 'api/v1') {
  $site_alias = drush_get_context('DRUSH_TARGET_SITE_ALIAS');
  $alias_settings = drush_sitealias_get_record($site_alias);

  $user = $alias_settings['sfapi-user'];
  $pass = $alias_settings['sfapi-password'];
  $site = $alias_settings['sfapi-site'];

  $siteurl = 'https://' . $user . ':' . $pass . '@' . $site;
  $url = $siteurl . '/' . $baseurl;

  return $url;
}
