<?php
/**
 * acsf function to execute a get request.
 */
function acsfapitools_getcmd($cmdurl = 'ping', $method = 'GET', $data = NULL) {
  $url = acsfapitools_conn() . '/' . $cmdurl;
  $headers = array(
    'Content-Type' => 'application/json',
    'Accept' => 'application/json',
  );
  $response = drupal_http_request($url, $headers, $method, $data, $retry = 3);
  $data = (string) $response->data;
  $data = json_decode($data);
  $code = (string) $response->code;

  if ($code !== '200') {
    drush_set_error(dt("HTTP response code: '!code'", array('!code' => $code)));
  }

  if (property_exists($data, 'server_time') && drush_get_context('DRUSH_VERBOSE')) {
    drush_log(dt("Server time: '!time'", array('!time' => $data->server_time)), 'notice');
  }

  if (drush_get_context('DRUSH_VERBOSE')) {
    drush_log(dt("Request url: '!url'", array('!url' => $url)));
    drush_log(dt("Request meathod: '!method'", array('!method' => $method)));
    drush_log(dt("Command: '!cmdurl'", array('!cmdurl' => $cmdurl)));
    drush_log(dt("HTTP response code: '!code'", array('!code' => $code)));
  }

  return $data;
}

/**
 * function to build request url fetching from alias
 *
 * @TODO cmd line parameters
 */
function acsfapitools_conn($baseurl = 'api/v1') {
  $site_alias = drush_get_context('DRUSH_TARGET_SITE_ALIAS');
  $alias_settings = drush_sitealias_get_record($site_alias);

  $user = $alias_settings['sfapi-user'];
  $pass = $alias_settings['sfapi-password'];
  $site = $alias_settings['sfapi-site'];

  $siteurl = 'https://' . $user . ':' . $pass . '@' . $site;
  $url = $siteurl . '/' . $baseurl;

  return $url;
}
